# Generated by Django 4.1 on 2022-09-07 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=None, verbose_name='date answered'),
            preserve_default=False,
        ),
    ]
