# Generated by Django 4.2.11 on 2024-04-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_survey_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='explanation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=20),
        ),
    ]
